module.exports = {
  screen: {
    flex: 1,
  },
  headerWrapper: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
  },
  avatarWrapper: {
    height: 50,
    width: 50,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#8992AB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  usernameWrapper: {
    marginLeft: 15,
  },
  alertWrapper: {
    height: 40,
    width: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#8992AB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentWrapper: {
    paddingBottom: 30,
  },
  categoriesWrapper: {},
  cardWrapper: {
    height: 130,
    width: 160,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: '#656565',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5.62,
    elevation: 8,
  },
  dietPlanWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginHorizontal: 20,
    borderRadius: 20,
    backgroundColor: '#E5F1FF',
    shadowColor: '#656565',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5.62,
    elevation: 8,
  },
  subHeaderText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#8992AB',
  },
  userNameText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#1B2D48',
  },
  titleText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 26,
    color: '#1B2D48',
    marginBottom: 10,
    marginLeft: 20,
  },
  cardText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    color: '#2F327D',
    textAlign: 'center',
    marginTop: 10,
    paddingHorizontal: 30,
  },
  dietTitleText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
    color: '#1B2D48',
  },
};
