# Generated by Django 4.0.9 on 2023-02-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=10, null=True),
        ),
    ]
