# Generated by Django 4.0.9 on 2023-04-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_oxygenrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygenrequest',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blood.patient'),
            preserve_default=False,
        ),
    ]
