# Generated by Django 4.0.9 on 2023-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_oxygenrequest_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
