# Generated by Django 4.0.9 on 2023-02-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_user_first_name_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
